# Generated by Django 5.2.4 on 2025-07-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_create', 'Can create records/entries'), ('can_delete', 'Can delete records/entries')], 'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom users'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
