"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$ta^)#fyk2u0_1($24*z!%j!8gh2#no46_(r!!o6m*#pet#x85'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'your_domain.com', 'localhost']



# ============================================================
# PRODUCTION SECURITY SETTINGS (Applied when DEBUG=False)
# ============================================================

if not DEBUG:
    # ---------------------------------------------
    # HTTPS Enforcement
    # ---------------------------------------------

    # Redirect all HTTP requests to HTTPS to ensure secure communication.
    # This setting ensures that all traffic is encrypted in transit.
    SECURE_SSL_REDIRECT = True

    # ---------------------------------------------
    # HTTP Strict Transport Security (HSTS)
    # ---------------------------------------------

    # Tells browsers to only communicate with the server over HTTPS for a given period.
    # Helps prevent protocol downgrade attacks and cookie hijacking.
    SECURE_HSTS_SECONDS = 31536000  # 1 year

    # Applies the HSTS policy to all subdomains as well (e.g., www.yoursite.com, api.yoursite.com).
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True

    # Preload your domain in major browsers’ HSTS preload list.
    # Requires submitting your domain to https://hstspreload.org
    SECURE_HSTS_PRELOAD = True

    # ---------------------------------------------
    # Secure Cookies
    # ---------------------------------------------

    # Ensures session cookies are only sent over HTTPS connections.
    # Prevents session hijacking via cookie theft over unsecured HTTP.
    SESSION_COOKIE_SECURE = True

    # Ensures CSRF cookies are only sent over HTTPS connections.
    # Helps protect against CSRF token interception attacks.
    CSRF_COOKIE_SECURE = True

    # ---------------------------------------------
    # Secure HTTP Headers
    # ---------------------------------------------

    # Protects against clickjacking by preventing your site from being embedded in an iframe.
    # 'DENY' is the strictest setting and disallows all framing.
    X_FRAME_OPTIONS = 'DENY'

    # Prevents the browser from MIME-sniffing the response and forces it to respect the Content-Type header.
    # Helps mitigate MIME-type confusion vulnerabilities.
    SECURE_CONTENT_TYPE_NOSNIFF = True

    # Enables the browser's built-in XSS filtering mechanism.
    # Although largely redundant in modern browsers, it adds a layer of legacy protection.
    SECURE_BROWSER_XSS_FILTER = True

    # ---------------------------------------------
    # Proxy Header (for deployments behind reverse proxy)
    # ---------------------------------------------

    # Informs Django that it should trust the 'X-Forwarded-Proto' header from a proxy (like Nginx)
    # to determine if the original request was HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
    'csp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware', # Content Security Policy middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --- Content Security Policy (CSP) Settings (via django-csp) ---
# Implemented using django-csp middleware to specify allowed content sources,
# significantly reducing the risk of XSS attacks by preventing browsers from
# loading unauthorized scripts, styles, or other resources.

CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': ("'self'",), # Allow content only from the same origin by default
        'script-src': ("'self'",), # Allow JavaScript only from the same origin
        'style-src': ("'self'", "'unsafe-inline'",), # Allow CSS from same origin and necessary inline styles
        'img-src': ("'self'", 'data:', 'https://placehold.co'), # Allow images from same origin, data URIs, and specific external placeholder service
        'font-src': ("'self'",), # Allow fonts only from the same origin
        'connect-src': ("'self'",), # Allow network connections (XHR, WebSockets) only to the same origin
        'object-src': ("'none'",), # Disallow <object>, <embed>, <applet> elements entirely
        'base-uri': ("'self'",), # Restrict base URL for relative URLs
        'form-action': ("'self'",), # Restrict form submission targets to the same origin
        'frame-ancestors': ("'self'",), # Prevent embedding this page in iframes from other domains
        # 'report-uri': '/csp-report/', # Optional: Configure a URL to receive CSP violation reports
    },
    # Optional: Set to True to only report violations without blocking them.
    # CONTENT_SECURITY_POLICY_REPORT_ONLY = True
}




ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'
AUTH_USER_MODEL = 'bookshelf.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'